/**
 * Katalog der auditpflichtigen Aktionen (ADR-010).
 *
 * Diese Liste MUSS deckungsgleich mit der Check-Constraint auf
 * public.audit_log.action sein. Ein Datenbanktest prüft das gegeneinander -
 * andernfalls würde ein neues Ereignis in der Oberfläche fehlen oder ein
 * Filterwert ins Leere laufen.
 */
export const AUDIT_ACTIONS = [
  'patient_record.viewed',
  // OPS-006: die Auskunft nach Art. 15 DSGVO ist ein Export klinischer Daten
  // und damit auditpflichtig (ADR-010 Punkt 2).
  'patient_record.exported',
  'audit_log.read',
  'patient.created',
  'patient.updated',
  'patient.status_changed',
  'patient.care_concluded',
  'patient.care_reopened',
  'legal_hold.placed',
  'legal_hold.released',
  'retention.applied',
  'retention.reapplied',
  'appointment.created',
  'appointment.updated',
  'appointment.rescheduled',
  'appointment.cancelled',
  'appointment.no_show',
  'appointment.completed',
  'appointment.documented',
  'appointment.reopened',
  'appointment.notified',
  'organization.appointment_grid_changed',
  'organization.documentation_deadline_changed',
  'staff_working_hours.created',
  'staff_working_hours.updated',
  'staff_working_hours.removed',
  'staff_working_hour_exception.created',
  'staff_working_hour_exception.updated',
  'staff_working_hour_exception.removed',
  'staff_member.created',
  'staff_member.updated',
  'staff_member.status_changed',
  'staff_account.invited',
  'staff_account.invitation_revoked',
  'staff_account.invitation_accepted',
  'staff_account.roles_changed',
  'staff_account.locked',
  'staff_account.unlocked',
  'staff_account.password_reset_requested',
  'account.password_changed',
  'account.sessions_ended',
  'account.mfa_enrolled',
  'account.mfa_removed',
  'treatment_note.created',
  'treatment_note.updated',
  'treatment_note.viewed',
  'treatment_note.finalized',
  'treatment_note.auto_finalized',
  'treatment_note.revised',
  'treatment_note.addendum_created',
  'treatment_note.history_viewed',
  // Bis GRD-001 geschrieben, seitdem nur noch gelesen: Auditzeilen werden
  // niemals umgeschrieben (ADR-010, ADR-020 Punkt 8).
  'prescription.viewed',
  'prescription.created',
  'prescription.updated',
  'prescription.deleted',
  'treatment_basis.viewed',
  'treatment_basis.created',
  'treatment_basis.updated',
  'treatment_basis.deleted',
  // CAL-022: ein Ereignis je Uebertragung, nicht je Termin.
  'treatment_basis.appointments_transferred',
  'patient_file.uploaded',
  'patient_file.link_issued',
  'patient_file.deleted',
  'patient_file.type_corrected',
  'storage_deletion.claimed',
  'storage_deletion.receipted',
  // G6c: nur abgewiesen - der erlaubte Weg protokolliert das Vormerken nicht,
  // die Ausfuehrung steht unter `claimed` und `receipted`.
  'storage_deletion.ordered',
  'text_snippet.created',
  'text_snippet.updated',
  'text_snippet.deleted',
  // ABR-001: Ein Preis entscheidet über eine Forderung; das Veröffentlichen
  // macht ihn unveränderlich.
  'service_catalog.version_created',
  'service_catalog.version_updated',
  'service_catalog.version_published',
  'service_catalog.version_deleted',
  // ABR-002: ein Ereignis je Vorgang, nicht je Leistung.
  'billable_service.recorded',
  'billable_service.removed',
  // ABR-000: der Absender der Rechnung.
  'organization.billing_profile_changed',
  // ABR-003a: der Empfänger ist eine eigene Entität (ADR-009 Punkt 2).
  'invoice_recipient.created',
  'invoice_recipient.updated',
  'invoice_recipient.deleted',
  // ABR-003: Das Ausstellen ist der Vorgang, nach dem nichts mehr zu ändern
  // ist (ADR-009 Punkt 9).
  'invoice.draft_created',
  'invoice.draft_deleted',
  'invoice.recipient_changed',
  'invoice.issued',
  // ABR-003c: Das Storno ist ein eigenes Dokument; die Rechnung selbst bleibt
  // unverändert (ADR-009 Punkt 9).
  'invoice.cancelled',
  // ABR-003d: Die Zahlungserinnerung ist ein Dokument ohne Stufe und ohne
  // Gebühr (IDEA-PRX-012).
  'invoice.reminder_created',
  // ABR-004: Eine Zahlung wird erfasst oder storniert — geändert oder
  // gelöscht wird sie nie (ADR-009 Punkt 12).
  'payment.recorded',
  'payment.voided',
  // OPS-007: die Einrichtung der einen Organisation, einmalig aus dem
  // SQL-Editor (ADR-003, ADR-010 Punkt 2).
  'organization.bootstrapped',
  // OPS-004: nur mit outcome 'denied' — das erfolgreiche Lesen der
  // Löschläufe bleibt ohne Eintrag, der abgewiesene Versuch nicht.
  'deletion_runs.read',
  // PAT-006: Datenschutzinformation, Behandlungsvertrag, Einwilligung und
  // Widerruf — ein Ereignis, Art und Zweck im Kontext.
  'patient_privacy.recorded',
  // G6b: nur mit outcome 'denied' — abgewiesene Lesezugriffe je Datenbereich.
  'appointments.read',
  'patient_directory.read',
  'treatment_bases.read',
  'treatment_evidence.read',
  'patient_files.read',
  'text_snippets.read',
  'invoicing.read',
  'billable_services.read',
  'legal_holds.read',
  'storage_deletion.read',
  // MAP-006a: Koordinate zur Adresse und Startort der Tagesroute (ANN-016).
  'patient.address_geocoded',
  'organization.tour_start_changed',
  // FRB-EPIC-002: erhobene Fragebögen (ANN-103).
  'questionnaire_response.created',
  'questionnaire_response.updated',
  'questionnaire_response.completed',
  'questionnaire_response.discarded',
  'questionnaire_response.viewed',
  // FRB-002e: Ereignisse im Verlauf (ANN-106).
  'patient_course_event.created',
  'patient_course_event.removed',
  'patient_course_event.viewed',
  // DOK-005a: Therapiebericht an die Verordner:in (ANN-121); der Druckknopf
  // gilt als Export (ADR-010 Punkt 2).
  'therapy_report.created',
  'therapy_report.updated',
  'therapy_report.completed',
  'therapy_report.discarded',
  'therapy_report.viewed',
  'therapy_report.exported',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const auditActionLabels: Record<AuditAction, string> = {
  'patient_record.viewed': 'Patientenakte geöffnet',
  'patient_record.exported': 'Auskunft aus der Akte erteilt',
  'audit_log.read': 'Auditlog gelesen',
  'patient.created': 'Patient:in angelegt',
  'patient.updated': 'Stammdaten geändert',
  'patient.status_changed': 'Versorgungsstatus geändert',
  'patient.care_concluded': 'Versorgung abgeschlossen',
  'patient.care_reopened': 'Abschluss der Versorgung zurückgenommen',
  'legal_hold.placed': 'Löschsperre gesetzt',
  'legal_hold.released': 'Löschsperre aufgehoben',
  'retention.applied': 'Löschlauf ausgeführt',
  'retention.reapplied': 'Löschungen nach Wiederherstellung nachgezogen',
  'appointment.created': 'Termin angelegt',
  'appointment.updated': 'Termin geändert',
  'appointment.rescheduled': 'Termin verschoben',
  'appointment.cancelled': 'Termin abgesagt',
  'appointment.no_show': 'Niemand angetroffen',
  'appointment.completed': 'Termin abgeschlossen',
  'appointment.documented': 'Termin dokumentiert',
  'appointment.reopened': 'Termin wieder geöffnet',
  'appointment.notified': 'Mitteilung an die Patient:in vermerkt',
  'organization.appointment_grid_changed': 'Praxisraster geändert',
  'organization.documentation_deadline_changed': 'Dokumentationsfrist geändert',
  'staff_working_hours.created': 'Wochenarbeitszeit angelegt',
  'staff_working_hours.updated': 'Wochenarbeitszeit geändert',
  'staff_working_hours.removed': 'Wochenarbeitszeit entfernt',
  'staff_working_hour_exception.created': 'Abweichung angelegt',
  'staff_working_hour_exception.updated': 'Abweichung geändert',
  'staff_working_hour_exception.removed': 'Abweichung aufgehoben',
  'staff_member.created': 'Mitarbeiter:in angelegt',
  'staff_member.updated': 'Mitarbeiterstammdaten geändert',
  'staff_member.status_changed': 'Beschäftigungsstatus geändert',
  'staff_account.invited': 'Zugang eingeladen',
  'staff_account.invitation_revoked': 'Einladung zurückgenommen',
  'staff_account.invitation_accepted': 'Einladung angenommen',
  'staff_account.roles_changed': 'Rollen geändert',
  'staff_account.locked': 'Zugang gesperrt',
  'staff_account.unlocked': 'Zugang entsperrt',
  'staff_account.password_reset_requested': 'Kennwort zurücksetzen angestoßen',
  'account.password_changed': 'Eigenes Kennwort geändert',
  'account.sessions_ended': 'Alle eigenen Sitzungen beendet',
  'account.mfa_enrolled': 'Zweiter Faktor eingerichtet',
  'account.mfa_removed': 'Zweiter Faktor entfernt',
  'treatment_note.created': 'Behandlungsdokumentation angelegt',
  'treatment_note.updated': 'Behandlungsdokumentation geändert',
  'treatment_note.viewed': 'Behandlungsdokumentation gelesen',
  'treatment_note.finalized': 'Behandlungsdokumentation finalisiert',
  'treatment_note.auto_finalized': 'Behandlungsdokumentation automatisch finalisiert',
  'treatment_note.revised': 'Behandlungsdokumentation korrigiert',
  'treatment_note.addendum_created': 'Nachtrag angelegt',
  'treatment_note.history_viewed': 'Änderungsverlauf gelesen',
  'text_snippet.created': 'Textbaustein angelegt',
  'text_snippet.updated': 'Textbaustein geändert',
  'text_snippet.deleted': 'Textbaustein gelöscht',
  'service_catalog.version_created': 'Preisliste angelegt',
  'service_catalog.version_updated': 'Preisliste geändert',
  'service_catalog.version_published': 'Preisliste in Kraft gesetzt',
  'service_catalog.version_deleted': 'Preislistenentwurf verworfen',
  'billable_service.recorded': 'Leistungen zum Termin erfasst',
  'billable_service.removed': 'Leistungen zum Termin entfernt',
  'organization.billing_profile_changed': 'Praxis-Stammdaten für Rechnungen geändert',
  'invoice_recipient.created': 'Rechnungsempfänger angelegt',
  'invoice_recipient.updated': 'Rechnungsempfänger geändert',
  'invoice_recipient.deleted': 'Rechnungsempfänger entfernt',
  'invoice.draft_created': 'Rechnungsentwurf angelegt',
  'invoice.draft_deleted': 'Rechnungsentwurf verworfen',
  'invoice.recipient_changed': 'Empfänger des Entwurfs gewählt',
  'invoice.issued': 'Rechnung ausgestellt',
  'invoice.cancelled': 'Rechnung storniert',
  'invoice.reminder_created': 'Zahlungserinnerung ausgestellt',
  'payment.recorded': 'Zahlung erfasst',
  'payment.voided': 'Zahlung storniert',
  'organization.bootstrapped': 'Praxis eingerichtet',
  'deletion_runs.read': 'Löschläufe gelesen',
  'patient_privacy.recorded': 'Datenschutzvermerk erfasst',
  'appointments.read': 'Termine gelesen',
  'patient_directory.read': 'Patientenverzeichnis durchsucht',
  'treatment_bases.read': 'Behandlungsgrundlagen gelesen',
  'treatment_evidence.read': 'Behandlungsnachweis gelesen',
  'patient_files.read': 'Dateien der Akte gelesen',
  'text_snippets.read': 'Textbausteine gelesen',
  'invoicing.read': 'Abrechnung gelesen',
  'billable_services.read': 'Leistungen gelesen',
  'legal_holds.read': 'Löschsperren gelesen',
  'storage_deletion.read': 'Löschaufträge der Ablage gelesen',
  'patient.address_geocoded': 'Adresse auf der Karte verortet',
  'organization.tour_start_changed': 'Startort der Touren geändert',
  'questionnaire_response.created': 'Fragebogen begonnen',
  'questionnaire_response.updated': 'Fragebogen-Entwurf geändert',
  'questionnaire_response.completed': 'Fragebogen abgeschlossen',
  'questionnaire_response.discarded': 'Fragebogen-Entwurf verworfen',
  'questionnaire_response.viewed': 'Fragebogen gelesen',
  'patient_course_event.created': 'Ereignis im Verlauf gesetzt',
  'patient_course_event.removed': 'Ereignis im Verlauf entfernt',
  'patient_course_event.viewed': 'Ereignisse im Verlauf gelesen',
  'therapy_report.created': 'Therapiebericht begonnen',
  'therapy_report.updated': 'Therapiebericht-Entwurf geändert',
  'therapy_report.completed': 'Therapiebericht abgeschlossen',
  'therapy_report.discarded': 'Therapiebericht-Entwurf verworfen',
  'therapy_report.viewed': 'Therapiebericht gelesen',
  'therapy_report.exported': 'Therapiebericht gedruckt',
  // Die alten Werte behalten ihren alten Wortlaut: Sie stehen an Zeilen, die
  // vor GRD-001 entstanden sind, und die betrafen nur Verordnungen.
  'prescription.viewed': 'Verordnung gelesen',
  'prescription.created': 'Verordnung erfasst',
  'prescription.updated': 'Verordnung geändert',
  'prescription.deleted': 'Verordnung gelöscht',
  'treatment_basis.viewed': 'Behandlungsgrundlage gelesen',
  'treatment_basis.created': 'Behandlungsgrundlage erfasst',
  'treatment_basis.updated': 'Behandlungsgrundlage geändert',
  'treatment_basis.deleted': 'Behandlungsgrundlage gelöscht',
  'treatment_basis.appointments_transferred': 'Termine auf diese Grundlage übertragen',
  'patient_file.uploaded': 'Datei zur Akte hinzugefügt',
  'patient_file.link_issued': 'Datei zum Öffnen freigegeben',
  'patient_file.deleted': 'Datei gelöscht',
  'patient_file.type_corrected': 'Dokumentart einer Datei korrigiert',
  'storage_deletion.claimed': 'Löschung in der Ablage freigegeben',
  'storage_deletion.receipted': 'Löschung in der Ablage quittiert',
  'storage_deletion.ordered': 'Verwaiste Objekte zum Löschen vorgemerkt',
};

export const auditSubjectLabels: Record<string, string> = {
  patient: 'Patient:in',
  organization: 'Organisation',
  appointment: 'Termin',
  staff_working_hours: 'Wochenarbeitszeit',
  staff_working_hour_exception: 'Arbeitszeitabweichung',
  staff_member: 'Mitarbeiter:in',
  treatment_note: 'Behandlungsdokumentation',
  prescription: 'Verordnung',
  treatment_basis: 'Behandlungsgrundlage',
  patient_file: 'Datei der Akte',
  questionnaire_response: 'Fragebogen',
  patient_course_event: 'Ereignis im Verlauf',
  therapy_report: 'Therapiebericht',
  storage_deletion_order: 'Löschauftrag der Ablage',
  service_catalog_version: 'Preisliste',
  invoice_recipient: 'Rechnungsempfänger',
  invoice: 'Rechnung',
  payment: 'Zahlung',
};

export const auditOutcomeLabels: Record<string, string> = {
  success: 'Erfolgreich',
  denied: 'Abgewiesen',
};
